Disables the keyboard in the presets. Closes #24
mbitsnbites/soundbox pull request #39
Opened 2017-10-06 19:14 UTC by vsariola

This prevents arrows and letter shortcuts from being used, so that the user doesn't accidentally overwrite instrument settings. Note that they still work when the select is open (when you see the whole list of instruments).

2017-10-06 19:16 UTC, esaruoho commented
@vsariola how much do you know about tab, css and js - i mean, is there some way of establishing Tab for a route which would be:
pattern order editor, pattern note editor, pattern effect command parameter editor and then back to pattern-order-editor? cos shift-tab/tab would really serve in these places much better than getting into that preset loader.

2017-10-07 08:17 UTC, mbitsnbites requested changes

2017-10-07 08:17 UTC, mbitsnbites commented on gui.js
> +	var presetIgnoreLetters = function (e)
You seem to be using the wrong indentation (tabs instead of spaces?). Please fix.

2017-10-07 08:17 UTC, mbitsnbites commented on gui.js
> +		if ((e.keyCode >= 65 && e.keyCode <= 90) || e.keyCode >= 37 || e.keyCode <= 40)
Why limit to A-Z and arrow keys? This kind of logic is often problematic (how about "=", "(", "[", non-US characters/keyboards ...?).

What happens if we ignore all key presses?

2017-10-07 08:18 UTC, mbitsnbites commented
Re tabs, there's also #22 ...

2017-10-07 10:34 UTC, vsariola commented
Ignores everything (no bad things seem to come from it), fixed indentation, rebased to tip and rewrote history.

2017-10-07 14:20 UTC, merged